version: "3.8"
services:
    gameserver:
        image: arp_gameserver:3.7-alpine
        build:
            context: .
            dockerfile: docker/gameserver.dockerfile
        ports: 
            - "30120:30120"
        stdin_open: true
        tty: true 
        container_name: arp_gameserver